# -*- coding: utf-8 -*-

"""
AO3 (Archive of Our Own) test fixtures

TODO: Populate with real HTML from AO3 story page
This can be generated by running:
  curl "https://archiveofourown.org/works/507461?view_adult=true" > ao3_work_page.html
"""

# Placeholder - replace with real AO3 HTML
ao3_work_page_html = """
<!DOCTYPE html>
<html>
<head>
    <title>Test Story - Archive of Our Own</title>
</head>
<body>
    <div id="main">
        <div id="workskin">
            <div class="preface group">
                <h2 class="title heading">
                    Test AO3 Story Title
                </h2>
                <h3 class="byline heading">
                    <a rel="author" href="/users/TestAuthor">TestAuthor</a>
                </h3>
                <div class="summary module">
                    <h3 class="heading">Summary:</h3>
                    <blockquote class="userstuff">
                        <p>This is a test summary for the AO3 story.</p>
                    </blockquote>
                </div>
            </div>

            <dl class="stats">
                <dt class="published">Published:</dt>
                <dd class="published">2023-01-15</dd>

                <dt class="status">Completed:</dt>
                <dd class="status">2023-06-20</dd>

                <dt class="words">Words:</dt>
                <dd class="words">50000</dd>

                <dt class="chapters">Chapters:</dt>
                <dd class="chapters">10/10</dd>

                <dt class="kudos">Kudos:</dt>
                <dd class="kudos">1500</dd>

                <dt class="bookmarks">Bookmarks:</dt>
                <dd class="bookmarks">350</dd>
            </dl>

            <dd class="rating tags">
                <ul class="commas">
                    <li><a class="tag" href="/works?rating=Mature">Mature</a></li>
                </ul>
            </dd>

            <dd class="warning tags">
                <ul class="commas">
                    <li><a class="tag" href="/works?warning=No+Archive+Warnings+Apply">No Archive Warnings Apply</a></li>
                </ul>
            </dd>

            <dd class="fandom tags">
                <ul class="commas">
                    <li><a class="tag" href="/tags/Harry%20Potter">Harry Potter - J. K. Rowling</a></li>
                </ul>
            </dd>

            <dd class="freeform tags">
                <ul class="commas">
                    <li><a class="tag" href="/tags/Time%20Travel">Time Travel</a></li>
                    <li><a class="tag" href="/tags/Fix-It">Fix-It</a></li>
                </ul>
            </dd>

            <div id="chapters">
                <div class="chapter">
                    <h3 class="title">Chapter 1: The Beginning</h3>
                    <div class="userstuff">
                        <p>This is the first chapter content.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
"""


# Chapter fixtures
ao3_chapter_1_html = """
<!DOCTYPE html>
<html>
<body>
    <div id="chapters">
        <div class="chapter">
            <h3 class="title">Chapter 1: The Beginning</h3>
            <div class="userstuff">
                <p>First sentence of chapter one.</p>
                <p>Middle content.</p>
                <p>Last sentence of chapter one.</p>
            </div>
        </div>
    </div>
</body>
</html>
"""

# Note: To generate real fixtures, run fanficfare locally and capture the HTML:
# import requests
# response = requests.get('https://archiveofourown.org/works/507461?view_adult=true')
# with open('tests/fixtures_ao3.py', 'w') as f:
#     f.write(f'ao3_work_page_html = """{response.text}"""')
