# -*- coding: utf-8 -*-

"""
FanFiction.Net (FFN) test fixtures

TODO: Populate with real HTML from FFN story page
This can be generated by running:
  curl "https://www.fanfiction.net/s/4536005/1/" > ffn_story_page.html
"""

# Placeholder - replace with real FFN HTML
ffn_story_page_html = """
<!DOCTYPE html>
<html>
<head>
    <title>Test FFN Story - FanFiction</title>
</head>
<body>
    <div id="profile_top">
        <b class="xcontrast_txt">Test FFN Story Title</b>
        <div>
            By: <a class="xcontrast_txt" href="/u/123456/TestAuthor">TestAuthor</a>
        </div>
        <div class="xcontrast_txt">
            Summary: This is a test summary for the FFN story.
        </div>
        <span class="xgray xcontrast_txt">
            Rated: Fiction M - English - Adventure/Fantasy - Harry P., Hermione G. -
            Chapters: 15 - Words: 125,000 - Reviews: 2,500 - Favs: 5,000 - Follows: 3,000 -
            Updated: Jun 15, 2023 - Published: Jan 1, 2023 - Status: Complete - id: 4536005
        </span>
    </div>

    <select id="chap_select" name="chapter">
        <option value="1" selected>1. Chapter One: The Start</option>
        <option value="2">2. Chapter Two: The Middle</option>
        <option value="3">3. Chapter Three: The End</option>
    </select>

    <div id="storytext" class="storytext xcontrast_txt nocopy">
        <p>This is the first chapter content of the FFN story.</p>
        <p>More story text here.</p>
    </div>
</body>
</html>
"""

# Chapter fixtures
ffn_chapter_1_html = """
<!DOCTYPE html>
<html>
<body>
    <div id="storytext" class="storytext xcontrast_txt nocopy">
        <p>First sentence of chapter one.</p>
        <p>Middle content of the chapter.</p>
        <p>Last sentence of chapter one.</p>
    </div>
</body>
</html>
"""

ffn_chapter_2_html = """
<!DOCTYPE html>
<html>
<body>
    <div id="storytext" class="storytext xcontrast_txt nocopy">
        <p>First sentence of chapter two.</p>
        <p>Middle content of chapter two.</p>
        <p>Last sentence of chapter two.</p>
    </div>
</body>
</html>
"""

# Note: To generate real fixtures, run fanficfare locally and capture the HTML:
# import requests
# response = requests.get('https://www.fanfiction.net/s/4536005/1/')
# with open('tests/fixtures_ffn.py', 'w') as f:
#     f.write(f'ffn_story_page_html = """{response.text}"""')
